name: on-push

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: set environment variables
      uses: allenevans/set-env@v2.0.0
    - uses: actions/setup-dotnet@v1
      with:
       dotnet-version: '3.1.100'
    - name: Build with dotnet
      run: dotnet build
